name: qmmp  # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.6.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Audio/Music player based on Qt with a user interface similar to Winamp or xmms # 79 char long summary
description: |
  This is an audio/music player based on Qt.
  The user interface is similar to Winamp or xmms, alternative user interfaces are also is available.
grade: stable # must be 'stable' to release into candidate/stable channels
#confinement: devmode # use 'strict' once you have the right plugs and slots
confinement: strict
parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libgtk2.0-0
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all

  qmmp:
    after: [desktop-qt5]
    source: https://qmmp.ylsoftware.com/files/qmmp/1.6/qmmp-1.6.2.tar.bz2
    build-packages: [
      g++,qtbase5-dev,
      qtbase5-dev-tools,
      qttools5-dev,
      libqt5x11extras5-dev,
      qtmultimedia5-dev,
      libtag1-dev,
      libmpg123-dev, #mpeg support 
      libwavpack-dev, #wav support
      libcdio-dev,
      libcdio-cdda-dev,
      libcdio-paranoia-dev,
      libflac-dev, #flac support 
      libvorbis-dev, #vorbis support
      libsoxr-dev,
      libopus-dev,
      libshout3-dev, 
      libcddb2-dev,
      libsndfile1-dev,
      libxcb1-dev,
      libprojectm-dev,
      libbs2b-dev,
      libarchive-dev
    ]
    stage-packages:
    - ffmpeg
    - mplayer
    - libdouble-conversion1
    - libfreetype6
    - libgl1
    - libglvnd0
    - libglx0
    - libgraphite2-3
    - libharfbuzz0b
    - libicu60
    - libpng16-16
    - libqt5core5a
    - libqt5dbus5
    - libqt5gui5
    - libqt5network5
    - libqt5sql5
    - libqt5widgets5
    - libx11-6
    - libxau6
    - libxcb1
    - libxdmcp6
    - libasyncns0
    - libflac8
    - libogg0
    - libpulse0
    - libqt5multimedia5
    - libqt5x11extras5
    - libsndfile1
    - libvorbis0a
    - libvorbisenc2
    - libglu1-mesa
    - libtag1v5-vanilla
    - tar
    - unzip
    - bzip2
    - gzip
    - curl
    - libmad0-dev
    - libopusfile-dev
    - libcddb2
    - libgpm2
    - libshout3
    - libarchive13
    - libftgl2
    - libglew2.0
    - libprojectm2v5
    - libslang2
    - freeglut3

    plugin: cmake
 
  cleanup:
    after: [qmmp]  # Make this part run last; list all your other parts here
    plugin: nil
    build-snaps: [core18]  # List all content-snaps and base snaps you're using here
    override-prime: |
      set -eux
      for snap in "core18"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  qmmp:
    desktop: share/applications/qmmp.desktop
    command: bin/qmmp
    command-chain: [bin/desktop-launch]
    plugs:
    - desktop
    - desktop-legacy
    - x11
    - wayland
    - unity7
    - home
    - network
    - opengl
    - audio-playback
    - pulseaudio
    - removable-media
    slots:
    - mpris



  
